version: "3.7"
services:
  the_actual_db:
    image: "mongo:4.0-xenial"
    ports:
      - "27017:27017"

  mongo:
    image: "mongo:4.0-xenial"
    depends_on:
      - the_actual_db
    volumes:
      - .:/work
    command: sh -c "sleep 2 && mongo mongodb://the_actual_db /work/hydrate.js"
   
